// DO NOT EDIT THIS FILE. IT IS AUTO-GENERATED BY "cmd/gen-db.go". //
/*
 * bot: Platform list, (C) 2017 Zoe.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package surferua

import (
	"math/rand"
)

func init() {
	platformTypeSize = 1
	// [Phone]
	platformSize = []int{ 2, }
	platformDB = [][]PlatformInfo{ 
		{ 
			{
				Name: "iOS",
				VersionInfo: VersionInfo{
					Major: Endpoint{Start: 6, End: 11},
					Minor: Endpoint{Start: 0, End: 3},
					Patch: Endpoint{Start: 0, End: 3},
				},
			},
			{
				Name: "Android",
				VersionInfo: VersionInfo{
					Major: Endpoint{Start: 4, End: 8},
					Minor: Endpoint{Start: 0, End: 4},
					Patch: Endpoint{Start: 0, End: 4},
				},
			},
		},
	}
}


// With type: Phone
func (ua *UserAgent)Phone() (*UserAgent) {
	ua.Platform = platformDB[0][rand.Intn(platformSize[0])].Random()
	return ua
}


// With target: iOS
func (ua *UserAgent)IOS() (*UserAgent) {
	ua.Platform = platformDB[0][0].Random()
	return ua
}
// With target: Android
func (ua *UserAgent)Android() (*UserAgent) {
	ua.Platform = platformDB[0][1].Random()
	return ua
}


